services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":${S3_WEB_DOCKER_PORT}"
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    ports:
      - "${S3_API_PORT}:${S3_API_DOCKER_PORT}"
      - "${S3_WEB_PORT}:${S3_WEB_DOCKER_PORT}"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
