--liquibase formatted sql

--changeset Mihail:1.0.0-create-notification-rules
create table if not exists notification_rules
(
    id                bigint generated by default as identity primary key,
    title             varchar(50)  not null,
    condition_type    varchar(20)  not null,
    condition_config  JSONB,
    recipients_config JSONB,
    message_text      varchar(500) not null,
    is_active         bool default title,
    created_by        bigint       not null,
    created_at        timestamp    not null,
    updated_at        timestamp
);