spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false
    change-log: db/changelog/main-changelog.xml

  mail:
    protocol: smtp
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL-USERNAME}
    password: ${MAIL-PASSWORD}
    ssl:
      enabled: true

springdoc:
  swagger-ui:
    path: swagger-ui/index.html

