--liquibase formatted sql

--changeset Mihail:1.0.0
create table if not exists storages
(
    id                bigint generated by default as identity primary key,
    name              varchar(50)  not null,
    description       varchar(500),
    location          varchar(255) not null,
    parent_storage_id bigint,
    created_by        bigint,
    created_at        timestamp default current_timestamp,
    updated_at        timestamp,
    constraint parent_storage_id_fk foreign key (parent_storage_id) references storages (id)
);