--liquibase formatted sql

--changeset Mihail:1.0.0-create-qrCodes
create table if not exists qr_codes
(
    id         bigint generated by default as identity primary key,
    qr_content varchar(500) not null unique,
    object_id  bigint,
    cell_id    bigint,
    storage_id bigint,
    created_at timestamp default current_timestamp,
    constraint qr_object_id_fk foreign key (object_id) references storage_objects (id),
    constraint qr_cell_id_fk foreign key (cell_id) references cells (id),
    constraint qr_storage_id_fk foreign key (storage_id) references storages (id)
);
