--liquibase formatted sql

--changeset Mihail:1.0.0-create-qrCodes
create table if not exists cells
(
    id         bigint generated by default as identity primary key,
    object_id  bigint,
    cell_id    bigint,
    storage_id bigint,
    created_at timestamp,
    constraint object_id_fk foreign key (object_id) references storage_objects (id),
    constraint cell_id_fk foreign key (cell_id) references cells (id),
    constraint storage_id_fk foreign key (storage_id) references storages (id)

);