--liquibase formatted sql

--changeset Mihail:1.0.0-create-notifications
create table if not exists notifications
(
    id      bigint generated by default as identity primary key,
    rule_id bigint       not null,
    message varchar(500) NOT NULL,
    status  varchar(20)  not null,
    sent_at timestamp    not null,
    constraint notifications_rule_fk foreign key (rule_id) references notification_rules (id) on delete cascade
);