--liquibase formatted sql

--changeset Mihail:1.0.0-create-objects
create table if not exists storage_objects
(
    id                bigint generated by default as identity primary key,
    type              varchar(50) not null,
    name              varchar(50) not null,
    description       varchar(500),
    photo_url         varchar(500),
    purchase_date     timestamp,
    purchase_location varchar(255),
    quantity          int         default 1,
    volume_per_unit   int         default 1,
    status            varchar(50) default 'ACTIVE',
    notes             varchar(500),
    storage_id        bigint      not null,
    cell_id           bigint,
    custom_attributes jsonb,
    created_by        bigint      not null,
    created_at        timestamp   default current_timestamp,
    constraint storage_id_fk foreign key (storage_id) references storages (id),
    constraint cell_id_fk foreign key (cell_id) references cells (id)
);