--liquibase formatted sql

--changeset Mihail:1.0.0-create-cells
create table if not exists cells
(
    id                bigint generated by default as identity primary key,
    name              varchar(50)  not null,
    description       varchar(500),
    location          varchar(255) not null,
    capacity int not null,
    storage_id bigint,
    parent_cell_id bigint,
    created_by        bigint,
    created_at        timestamp default current_timestamp,
    updated_at        timestamp,
    constraint storage_id_fk foreign key (storage_id) references storages (id),
    constraint parent_cell_id_fk foreign key (parent_cell_id) references cells (id)
);